!**************************************************
! Preliminary Requirements
!**************************************************
!
volumetric_flow=13.9162                                    ! volumetric flow (Q)
flow_velocity=31.5                                  ! flow velocity (v)
!
!**************************************************
! Vibration analysis 
!**************************************************
! 
! # of Modes
modes=10